### PR TITLE
Add Docker environment & web demo

### PR DESCRIPTION
**Pull request by bfirsh**
Hey @Lornatang! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! View it here: https://replicate.ai/lornatang/cyclegan-pytorch

You can claim your page by signing in with GitHub, then we'll feature it on our site.

In case you're wondering who I am, I'm from [Replicate](https://replicate.ai/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. :)

### CODE REVIEW

**Comment by Lornatang** [comment]
Very thank you @bfirsh !

**Comment by bfirsh** [comment]
Thanks for merging! I'm so glad it is helpful. 😄

[Here's a link to claim your page](https://replicate.ai/login/github/?next=/jiupinjia/stylized-neural-painting-oil?published=1) if you want to edit it. You can change the description, add examples, and stuff. We'll also feature it on our explore page and twitter account!

**Comment by Lornatang** [comment]
Too busy at the moment~, I will continue to pay attention to it in the future, thank you for your contribution, and many algorithms in this library should be updated.

**Comment by zeke** [comment]
Wow this is a cool model! ✨ 🦓 ✨ 

> Too busy at the moment

Hey @Lornatang 👋🏼 that makes sense, I can see you're pretty busy making contributions to the GAN community. Just so you know, it only takes a [single click to claim your model](https://replicate.ai/login/github/?next=/jiupinjia/stylized-neural-painting-oil?published=1) with GitHub. We'd love to be able to feature it.

**Pull request merged**
